// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxem8XuE_nczgYsvxtb2JboSuv7zlQaDE',
    appId: '1:331121986086:web:d8835e578501f5a870b4e7',
    messagingSenderId: '331121986086',
    projectId: 'ntexpress0',
    authDomain: 'ntexpress0.firebaseapp.com',
    storageBucket: 'ntexpress0.appspot.com',
    measurementId: 'G-49NP70LGXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCWlOZm-QowL2mq2XxNb5EACPO1dFk_9Y',
    appId: '1:331121986086:android:aa2615b303484b0570b4e7',
    messagingSenderId: '331121986086',
    projectId: 'ntexpress0',
    storageBucket: 'ntexpress0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8aEiMMgPRWkNblf80WMWk9CUFCuUKOi4',
    appId: '1:331121986086:ios:c239f7fa2e653e7570b4e7',
    messagingSenderId: '331121986086',
    projectId: 'ntexpress0',
    storageBucket: 'ntexpress0.appspot.com',
    iosClientId: '331121986086-v2ubko0l3b5v5p7auf9qu2hoed8ailv6.apps.googleusercontent.com',
    iosBundleId: 'com.topbusiness.nte',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8aEiMMgPRWkNblf80WMWk9CUFCuUKOi4',
    appId: '1:331121986086:ios:71a1a096004a05c970b4e7',
    messagingSenderId: '331121986086',
    projectId: 'ntexpress0',
    storageBucket: 'ntexpress0.appspot.com',
    iosClientId: '331121986086-5k25om6j85civf9ce2e02ucu3co78or0.apps.googleusercontent.com',
    iosBundleId: 'com.topbusiness.nte.RunnerTests',
  );
}
